version: '3.4'

volumes:
  mysql: {}

services:
  mysql:
    image: mysql:8
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: twitter
    volumes:
      - mysql:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: docker/dockerfile
    restart: on-failure
    tty: true
    stdin_open: true
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app
    depends_on:
      - mysql
